seq_dataset 214
seq_dataset_val 234
Train epoch 1/200
  0% 0/1000 [00:00<?, ?it/s]  0% 0/1000 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 277, in <module>
    main()
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 193, in main
    closs, rloss, loss = model.step(epoch, dataset,anchors, i,  train=True)
  File "/home/zuern/SiamRPN-PyTorch/train/net.py", line 71, in step
    pred_score, pred_regression = self.net(template_rgb, detection_rgb, template_ir, detection_ir)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zuern/SiamRPN-PyTorch/tracking/network.py", line 239, in forward
    template_feature = self.featureExtract(template_rgb, template_ir)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zuern/SiamRPN-PyTorch/tracking/network.py", line 90, in forward
    x_v = self.conv1_ir(x_v)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 96 1 11 11, expected input[32, 3, 127, 127] to have 1 channels, but got 3 channels instead
