seq_dataset 214
seq_dataset_val 20
Train epoch 1/200
  0% 0/1000 [00:00<?, ?it/s]  0% 0/1000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/zuern/SiamRPN-PyTorch/train/train.py", line 294, in <module>
    main()
  File "/home/zuern/SiamRPN-PyTorch/train/train.py", line 173, in main
    for i, dataset in enumerate(train_loader):
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zuern/SiamRPN-PyTorch/train/data_rgbt.py", line 525, in __getitem__
    regression_target, conf_target = self._target()
  File "/home/zuern/SiamRPN-PyTorch/train/data_rgbt.py", line 439, in _target
    binary_target = self.compute_binary_target(self.anchors)
AttributeError: 'TrainDataLoaderRGBT' object has no attribute 'compute_binary_target'

